<?php

return [
    'name' => 'AppSetting',
    'icon' => 'c-sidebar-nav-icon fas fa-cog',
    'basic'=>[
    	'email' => env('APP_EMAIL', ''),
    	'phone' => env('APP_PHONE', ''),
    	'address' => env('APP_ADDRESS', ''),
        'map_key' => env('GOOGLE_MAP',''),
        // 'main_logo' => env('MAIN_LOGO', 'https://tea.com/app_data/main_logo.png'),
        'main_logo' => env('MAIN_LOGO', ''),
        'app_name'  => env('APP_NAME', ''),
        'facebook_link'  => env('FB_LINK', ''),
    ],
    'payment' => [
    	'2c2p' =>[
    		'enable' => env('2C2P_ENABLE',true),
    		'charge' => env('2C2P_CHARGE',''),
            'charge_type' => env('2C2P_CHARGE_TYPE',''),
            'version' => env('2C2P_VERSION','2'),
            'currency' => env('2C2P_CURRENCY','MMK'),
            'secret_key' => env('2C2P_SECRET_KEY',''),
            'merchant_id' => env('2C2P_MERCHANT_ID',''),
    		'payment_url' => env('2C2P_PAYMENT_URL','https://example.com'),
            'frontend_url' => env('2C2P_FRONTEND_URL','https://example.com'),
    		'backend_url' => env('2C2P_BACKEND_URL',''),
    	],
    	'kbz' =>[
    		'enable' => env('KBZ_ENABLE',true),
            'charge' => env('KBZ_CHARGE',''),
            'charge_type' => env('KBZ_CHARGE_TYPE',''),
            'version' => env('KBZ_VERSION','2'),
            'currency' => env('KBZ_CURRENCY','MMK'),
            'merchant_key' => env('KBZ_MERCHANT_KEY','AAAAA'),
            'app_id' => env('KBZ_APP_ID',''),
            'merchant_code' => env('KBZ_MERCHANT_CODE',''),
            'merchant_id' => env('KBZ_MERCHANT_ID',''),
            'payment_url' => env('KBZ_PAYMENT_URL','https://example.com'),
            'frontend_url' => env('KBZ_FRONTEND_URL','https://example.com'),
            'backend_url' => env('KBZ_BACKEND_URL',''),
    	],
        'cod' =>[
            'enable' => env('COD_ENABLE',''),
            'charge' => env('COD_CHARGE',''),
            'charge_type' => env('COD_CHARGE_TYPE',''),
            'note' => env('COD_NOTE',''),
        ],
    ],
    'email' => [
        'mail_driver' => env('MAIL_DRIVER', 'Smtp'),
        'mail_host' => env('MAIL_HOST', 'smtp.mailtrap.io'),
        'mail_port' => env('MAIL_PORT', '587'),
        'mail_username' => env('MAIL_USERNAME', '7d41168bba76b9'),
        'mail_password' => env('MAIL_PASSWORD', '338a6d5b5f94cd'),
        'mail_encryption' => env('MAIL_ENCRYPTION', 'tls'),
    ],
];
